export const PIZZA_SIZE_REPOSITORY = 'PIZZA_SIZE_REPOSITORY'
export const PIZZA_FLAVOR_REPOSITORY = 'PIZZA_FLAVOR_REPOSITORY'
export const PIZZA_PERSONALIZATION_REPOSITORY = 'PIZZA_PERSONALIZATION_REPOSITORY'