export const FIND_PIZZA_SIZES_FACTORY = 'FIND_PIZZA_SIZES_FACTORY'
export const FIND_PIZZA_FLAVORS_FACTORY = 'FIND_PIZZA_FLAVORS_FACTORY'
export const FIND_PIZZA_PERSONALIZATIONS_FACTORY = 'FIND_PIZZA_PERSONALIZATIONS_FACTORY'